import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {useState} from "react";
import {CounterComponent} from "./components/counter/CounterComponent";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const [show, setShow] = useState(true)

    const toggle = () => {
        setShow(!show)
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <div className={styles.cont} >
              <div><button style={{marginTop: '30px'}} className={styles.btn} onClick={toggle}>Schovat počítadlo</button></div>
              {show ? <CounterComponent /> : ''}
          </div>
      </main>
    </>
  )
}
